#!/bin/bash

ELASTIC_KEY=rmpnLwME4FNZT2M8XJQf

curl -X PUT -u elastic:$ELASTIC_KEY -k "https://localhost:9200/test2?pretty" -H 'Content-Type: application/json' -d'
{
  "settings": {
    "index": {
      "number_of_shards": 1,  
      "number_of_replicas": 0 
    }
  }
}
'
